
DECLARE @result NVARCHAR(max)

BEGIN
EXEC DBA.dbo.ControlTriggersTest @esquema = 'dbo', @nombreTabla= 'controlDC', @Respuesta = @result OUTPUT;

SELECT @result

END


SELECT 
--        DISTINCT FECHA_ENVIO_SERVICIO, JSON, JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.NROMOVFISCAL'), CONCAT('UPDATE dbafv.movcomercial SET SALDO=',JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.SALDO_DOLAR'), ', SALDO_D=',JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.SALDO_LOCAL'),' WHERE NROMOVFISCAL=',JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.NROMOVFISCAL'),';')
-- DISTINCT CONCAT('UPDATE dbafv.movcomercial SET SALDO=',JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.SALDO_DOLAR'), ', SALDO_D=',JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.SALDO_LOCAL'),' WHERE NROMOVFISCAL=',JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.NROMOVFISCAL'),';')
       JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.NROMOVFISCAL') as NROMOVFISCAL_movComercial,
       JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.ID') as ID_movcomercial,        
       JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.IDTRANSACCION') as IDTRANSACCION_movtransaccion,
       JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.DOCUMENTO_ORIGEN') as DOCUMENTO_ORIGEN_movtransaccion, 
       ENTIDAD , JSON , TIPO_SERVICIO , FECHA_ENVIO_SERVICIO , API_RESPONSE, API
FROM PRODUSOFT.FEBECA.PS_AFV_JSON j (NOLOCK)
WHERE ENTIDAD IN ('DOCUMENTOS_COMERCIALES')
 AND CAST(FECHA_ENVIO_SERVICIO AS DATE) >= '2024-02-01'
 -- AND TIPO_SERVICIO ='POST' 
 AND (
        JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.NROMOVFISCAL') IN (
'06643857', '06643858', '06643859'
        )
/*        OR 

        JSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.IDTRANSACCION') IN (
        '657113'
        )*/
);

SELECT *
FROM PRODUSOFT.[GLOBAL].PS_AFV_JSON j (NOLOCK)
WHERE ENTIDAD LIKE '%ARTICULO%'
 AND CAST(FECHA_ENVIO_SERVICIO AS DATE) >= '2024-02-25'
and 	jSON_VALUE(CAST(JSON AS NVARCHAR(MAX)), '$.ID') IN ('114849');
