-- No sincronizados hasta final de Junio
SELECT
	'', 
	'',
	'FAC' AS 'Tipo de documento',
	--dc.documento AS 'Número documento', 
	--ret.DOCUMENTO AS 'Número documento_RET', 
	CASE
	    WHEN ret.DOCUMENTO < 03199587 THEN CONCAT('A-',ret.DOCUMENTO)
	    ELSE ret.DOCUMENTO
	END AS 'Número documento_RET',
	'' AS 'Consecutivo Talonario', 
	ret.COMPROBANTE_RETENCION  AS 'Número de Comprobante Retención',
	ret.MONTO_RETENIDO_BOLIVARES AS 'Monto IVA retenido',
	0.00 AS 'Porcentaje de Retención',
	ret.FECHA_APLICACION_RETENCION AS 'Fecha aplicación retención',
	ret.FECHA_COMPROBANTE_RETENCION AS 'Fecha de comprobante de retención'
FROM 
(SELECT 
		TIPO,
		SUBTIPO,
		CODIGO_RETENCION,
		DETALLE_RETENCION,
		COMPROBANTE_RETENCION,
		MONTO_RETENCION,
		FECHA_APLICACION_RETENCION,
		FECHA_COMPROBANTE_RETENCION,
	-- CODIGO_RETENCION,
	--COMPROBANTE_RETENCION,
	-- DETALLE_RETENCION,
	MAX(CASE WHEN row_number = 1 THEN DETALLES_DOC END) AS DOCUMENTO,
	MAX(CASE WHEN row_number = 2 THEN DETALLES_DOC END) AS MONTO_RETENIDO_DOLAR,
    MAX(CASE WHEN row_number = 3 THEN DETALLES_DOC END) AS MONTO_RETENIDO_BOLIVARES
FROM
(
SELECT 
	*,
	ROW_NUMBER() OVER (PARTITION BY CODIGO_RETENCION,DETALLE_RETENCION ORDER BY DETALLE_RETENCION) AS row_number
FROM
	(
	SELECT 
		TIPO,
		SUBTIPO,
		CODIGO_RETENCION,
		DETALLES_RETENCION,
		DETALLE_RETENCION,
		COMPROBANTE_RETENCION,
		MONTO_RETENCION,
		FECHA_APLICACION_RETENCION,
		FECHA_COMPROBANTE_RETENCION,
		TRIM(VALUE) AS 'DETALLES_DOC'
	FROM 
		(
		SELECT
			dc.tipo AS 'TIPO',
			dc.subtipo AS 'SUBTIPO',
			dc.DOCUMENTO AS 'CODIGO_RETENCION',
			dc.NOTAS AS 'DETALLES_RETENCION',
			value AS 'DETALLE_RETENCION',
			RIGHT(U_U_COMPROBANTE,8) AS 'COMPROBANTE_RETENCION',
			MONTO_LOCAL AS 'MONTO_RETENCION',
			fecha_aprobacion AS 'FECHA_APLICACION_RETENCION',
			U_FECHA_RETENCION AS 'FECHA_COMPROBANTE_RETENCION'
		FROM
			SOFTLANDPRD.BEVAL.DOCUMENTOS_CC dc
		INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE c ON
			dc.CLIENTE = c.CLIENTE
		INNER JOIN SOFTLANDPRD.BEVAL.SUBTIPO_DOC_CC sdc ON
			dc.SUBTIPO = sdc.SUBTIPO
		CROSS APPLY STRING_SPLIT( CONCAT('', dc.NOTAS),',')
		WHERE
			dc.DOCUMENTO like 'RET%'
			AND dc.SUBTIPO in (9)
			and value != 'Retenciones Ventas'
			and fecha_aprobacion<'2023-07-01' 
			AND dc.NOTAS IS NOT NULL
			AND TRIM(CONCAT('',dc.NOTAS)) != ''
			AND dc.NOTAS NOT LIKE 'Aplicación%'
			AND dc.U_FECHA_RETENCION IS NOT NULL
			AND dc.NOTAS LIKE 'Retenciones Ventas ,%'
			AND dc.ANULADO = 'N'
			AND dc.U_SINCRONIZADO = 'N'
		) ret
	CROSS APPLY STRING_SPLIT( CONCAT('', DETALLE_RETENCION),'-')
	) DET
) subquery
GROUP BY 
		TIPO,
		SUBTIPO,
		CODIGO_RETENCION,
		DETALLE_RETENCION,
		COMPROBANTE_RETENCION,
		MONTO_RETENCION,
		FECHA_APLICACION_RETENCION,
		FECHA_COMPROBANTE_RETENCION
) AS RET
	WHERE 	RET.DOCUMENTO >= 01062243
;


-- SINCRONIZADOS HASTA 01-04-2023
SELECT
	'', 
	'',
	'FAC' AS 'Tipo de documento',
	--dc.documento AS 'Número documento', 
	--ret.DOCUMENTO AS 'Número documento_RET', 
	CASE
	    WHEN ret.DOCUMENTO < 03199587 THEN CONCAT('A-',ret.DOCUMENTO)
	    ELSE ret.DOCUMENTO
	END AS 'Número documento_RET',
	'0' AS 'Consecutivo Talonario', 
	ret.COMPROBANTE_RETENCION  AS 'Número de Comprobante Retención',
	--ret.MONTO_RETENIDO_BOLIVARES AS 'Monto IVA retenido',
	CAST(ret.MONTO_RETENIDO_BOLIVARES AS DECIMAL(22, 2)) AS 'Monto IVA retenido',
	'' AS 'Porcentaje de Retención',
	ret.FECHA_APLICACION_RETENCION AS 'Fecha aplicación retención',
	ret.FECHA_COMPROBANTE_RETENCION AS 'Fecha de comprobante de retención'
FROM 
(SELECT 
		TIPO,
		SUBTIPO,
		CODIGO_RETENCION,
		DETALLE_RETENCION,
		COMPROBANTE_RETENCION,
		MONTO_RETENCION,
		CONVERT(varchar,FECHA_APLICACION_RETENCION,103) as FECHA_APLICACION_RETENCION,
		CONVERT(varchar,FECHA_COMPROBANTE_RETENCION,103) as FECHA_COMPROBANTE_RETENCION,
	-- CODIGO_RETENCION,
	--COMPROBANTE_RETENCION,
	-- DETALLE_RETENCION,
	MAX(CASE WHEN row_number = 1 THEN DETALLES_DOC END) AS DOCUMENTO,
	MAX(CASE WHEN row_number = 2 THEN DETALLES_DOC END) AS MONTO_RETENIDO_DOLAR,
    MAX(CASE WHEN row_number = 3 THEN DETALLES_DOC END) AS MONTO_RETENIDO_BOLIVARES
FROM
(
SELECT 
	*,
	ROW_NUMBER() OVER (PARTITION BY CODIGO_RETENCION,DETALLE_RETENCION ORDER BY DETALLE_RETENCION) AS row_number
FROM
	(
	SELECT 
		TIPO,
		SUBTIPO,
		CODIGO_RETENCION,
		DETALLES_RETENCION,
		DETALLE_RETENCION,
		COMPROBANTE_RETENCION,
		MONTO_RETENCION,
		FECHA_APLICACION_RETENCION,
		FECHA_COMPROBANTE_RETENCION,
		TRIM(VALUE) AS 'DETALLES_DOC'
	FROM 
		(
		SELECT
			dc.tipo AS 'TIPO',
			dc.subtipo AS 'SUBTIPO',
			dc.DOCUMENTO AS 'CODIGO_RETENCION',
			dc.NOTAS AS 'DETALLES_RETENCION',
			value AS 'DETALLE_RETENCION',
			RIGHT(U_U_COMPROBANTE,8) AS 'COMPROBANTE_RETENCION',
			MONTO_LOCAL AS 'MONTO_RETENCION',
			fecha_aprobacion AS 'FECHA_APLICACION_RETENCION',
			U_FECHA_RETENCION AS 'FECHA_COMPROBANTE_RETENCION'
		FROM
			SOFTLANDPRD.BEVAL.DOCUMENTOS_CC dc
		INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE c ON
			dc.CLIENTE = c.CLIENTE
		INNER JOIN SOFTLANDPRD.BEVAL.SUBTIPO_DOC_CC sdc ON
			dc.SUBTIPO = sdc.SUBTIPO
		CROSS APPLY STRING_SPLIT( CONCAT('', dc.NOTAS),',')
		WHERE
			dc.DOCUMENTO like 'RET%'
			AND dc.SUBTIPO in (9)
			and value != 'Retenciones Ventas'
			and fecha_aprobacion<'2023-04-01' 
			AND dc.NOTAS IS NOT NULL
			AND TRIM(CONCAT('',dc.NOTAS)) != ''
			AND dc.NOTAS NOT LIKE 'Aplicación%'
			AND dc.U_FECHA_RETENCION IS NOT NULL
			AND dc.NOTAS LIKE 'Retenciones Ventas ,%'
			AND dc.ANULADO = 'N'
			AND dc.U_SINCRONIZADO = 'S'
		) ret
	CROSS APPLY STRING_SPLIT( CONCAT('', DETALLE_RETENCION),'-')
	) DET
) subquery
GROUP BY 
		TIPO,
		SUBTIPO,
		CODIGO_RETENCION,
		DETALLE_RETENCION,
		COMPROBANTE_RETENCION,
		MONTO_RETENCION,
		FECHA_APLICACION_RETENCION,
		FECHA_COMPROBANTE_RETENCION
) AS RET
	WHERE 	RET.DOCUMENTO >= 01062243
;





-- Tests 
SELECT 
		TIPO,
		SUBTIPO,
		CODIGO_RETENCION,
		DETALLE_RETENCION,
		COMPROBANTE_RETENCION,
		MONTO_RETENCION,
		FECHA_APLICACION_RETENCION,
		FECHA_COMPROBANTE_RETENCION,
	-- CODIGO_RETENCION,
	--COMPROBANTE_RETENCION,
	-- DETALLE_RETENCION,
	MAX(CASE WHEN row_number = 1 THEN DETALLES_DOC END) AS DOCUMENTO,
	MAX(CASE WHEN row_number = 2 THEN DETALLES_DOC END) AS MONTO_RETENIDO_DOLAR,
    MAX(CASE WHEN row_number = 3 THEN DETALLES_DOC END) AS MONTO_RETENIDO_BOLIVARES
FROM
(
SELECT 
	*,
	ROW_NUMBER() OVER (PARTITION BY CODIGO_RETENCION,DETALLE_RETENCION ORDER BY DETALLE_RETENCION) AS row_number
FROM
	(
	SELECT 
		TIPO,
		SUBTIPO,
		CODIGO_RETENCION,
		DETALLES_RETENCION,
		DETALLE_RETENCION,
		COMPROBANTE_RETENCION,
		MONTO_RETENCION,
		FECHA_APLICACION_RETENCION,
		FECHA_COMPROBANTE_RETENCION,
		TRIM(VALUE) AS 'DETALLES_DOC'
	FROM 
		(
		SELECT
			dc.tipo AS 'TIPO',
			dc.subtipo AS 'SUBTIPO',
			dc.DOCUMENTO AS 'CODIGO_RETENCION',
			dc.NOTAS AS 'DETALLES_RETENCION',
			value AS 'DETALLE_RETENCION',
			RIGHT(U_U_COMPROBANTE,8) AS 'COMPROBANTE_RETENCION',
			MONTO_LOCAL AS 'MONTO_RETENCION',
			fecha_aprobacion AS 'FECHA_APLICACION_RETENCION',
			U_FECHA_RETENCION AS 'FECHA_COMPROBANTE_RETENCION'
		FROM
			SOFTLANDPRD.BEVAL.DOCUMENTOS_CC dc
		INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE c ON
			dc.CLIENTE = c.CLIENTE
		INNER JOIN SOFTLANDPRD.BEVAL.SUBTIPO_DOC_CC sdc ON
			dc.SUBTIPO = sdc.SUBTIPO
		CROSS APPLY STRING_SPLIT( CONCAT('', dc.NOTAS),',')
		WHERE
			dc.DOCUMENTO like 'RET%'
			AND dc.SUBTIPO in (9)
			and value != 'Retenciones Ventas'
			and fecha_aprobacion<'2023-07-01' 
			AND dc.NOTAS IS NOT NULL
			AND TRIM(CONCAT('',dc.NOTAS)) != ''
			AND dc.NOTAS NOT LIKE 'Aplicación%'
			AND dc.U_FECHA_RETENCION IS NOT NULL
			AND dc.NOTAS LIKE 'Retenciones Ventas ,%'
			AND dc.ANULADO = 'N'
			AND dc.U_SINCRONIZADO = 'N'
		) ret
	CROSS APPLY STRING_SPLIT( CONCAT('', DETALLE_RETENCION),'-')
	) DET
) subquery
GROUP BY 
		TIPO,
		SUBTIPO,
		CODIGO_RETENCION,
		DETALLE_RETENCION,
		COMPROBANTE_RETENCION,
		MONTO_RETENCION,
		FECHA_APLICACION_RETENCION,
		FECHA_COMPROBANTE_RETENCION;
	
-- ------------------------------------------
