	
SELECT
	ISNULL(DCC.DOCUMENTO, F.FACTURA),
	ISNULL(DCC.TIPO, F.TIPO_DOCUMENTO) AS doc_type,
	ISNULL(DCC.FECHA_DOCUMENTO , F.FECHA_RIGE) AS doc_date,
	ISNULL(DCC.VENDEDOR, F.VENDEDOR) AS seller_id,
	C.ZONA AS zone_code,
	C.NOMBRE AS client_name,
	C.E_MAIL AS client_email,
	V.NOMBRE AS seller_name,
	V.E_MAIL AS seller_email
FROM
	SOFTLANDPRD.BEVAL.DOCUMENTOS_CC DCC WITH (NOLOCK)
RIGHT JOIN 
	SOFTLANDPRD.BEVAL.FACTURA F WITH (NOLOCK) ON DCC.DOCUMENTO = F.FACTURA 
INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE C WITH (NOLOCK) ON
	(DCC.CLIENTE = C.CLIENTE or F.CLIENTE = C.CLIENTE)
INNER JOIN SOFTLANDPRD.BEVAL.VENDEDOR V WITH(NOLOCK) ON
	(DCC.VENDEDOR = V.VENDEDOR OR F.VENDEDOR = V.VENDEDOR)
WHERE
	F.FACTURA IN('03222801') OR DCC.DOCUMENTO IN('03222801')
	
SELECT TOP 1 query.*
FROM (SELECT
	DCC.DOCUMENTO AS doc_number,
	DCC.TIPO AS doc_type,
	DCC.FECHA_DOCUMENTO AS doc_date,
	DCC.VENDEDOR AS seller_id,
	V.NOMBRE AS seller_name,
	C.NOMBRE AS client_name,
	C.ZONA AS zone_code,
	C.E_MAIL AS client_email,
	V.E_MAIL AS seller_email
FROM
	SOFTLANDPRD.BEVAL.DOCUMENTOS_CC DCC WITH (NOLOCK)
INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE C ON
	DCC.CLIENTE = C.CLIENTE
INNER JOIN SOFTLANDPRD.BEVAL.VENDEDOR V WITH (NOLOCK) ON
	DCC.VENDEDOR = V.VENDEDOR
WHERE
	DCC.DOCUMENTO IN('03205122')
	AND DCC.TIPO = 'FAC'
UNION
SELECT
	F.FACTURA AS doc_number,
	--DCC.TIPO_DOCUMENTO AS doc_type,
	CASE
	    WHEN F.TIPO_DOCUMENTO = 'F' THEN 'FAC'
	    WHEN F.TIPO_DOCUMENTO = 'D' THEN 'N/C'
	    WHEN F.TIPO_DOCUMENTO = 'C' THEN 'N/D'
	    ELSE 'FAC'
	END AS doc_type,
	F.FECHA_RIGE AS doc_date,
	F.VENDEDOR AS seller_id,
	V.NOMBRE AS seller_name,
	C.NOMBRE AS client_name,
	C.ZONA AS zone_code,
	C.E_MAIL AS client_email,
	V.E_MAIL AS seller_email
FROM
	SOFTLANDPRD.BEVAL.FACTURA F WITH (NOLOCK)
INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE C WITH (NOLOCK) ON
	F.CLIENTE = C.CLIENTE
INNER JOIN SOFTLANDPRD.BEVAL.VENDEDOR V WITH(NOLOCK) ON
	F.VENDEDOR = V.VENDEDOR
WHERE
	F.FACTURA IN('03222801')
) query
	
	03205122
	03222801



SELECT ${queryParams.getDocuments.fields.toString()} 
FROM ${DB}.DOCUMENTOS_CC DCC (NOLOCK) 
INNER JOIN ${DB}.CLIENTE C ON DCC.CLIENTE = C.CLIENTE 
INNER JOIN ${DB}.VENDEDOR V (NOLOCK) ON DCC.VENDEDOR = V.VENDEDOR 
WHERE 
DCC.TIPO = '${data.params.doc_type}' 
AND DCC.DOCUMENTO IN(${parseId(data.params.doc_number, false)})`;
	


SELECT
	DCC.DOCUMENTO AS doc_number,
	DCC.TIPO AS doc_type,
	DCC.FECHA_DOCUMENTO AS doc_date,
	DCC.VENDEDOR AS seller_id,
	V.NOMBRE AS seller_name,
	C.NOMBRE AS client_name,
	C.ZONA AS zone_code,
	C.E_MAIL AS client_email,
	V.E_MAIL AS seller_email
FROM
	SOFTLANDPRD.BEVAL.DOCUMENTOS_CC DCC (NOLOCK)
INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE C ON
	DCC.CLIENTE = C.CLIENTE
INNER JOIN SOFTLANDPRD.BEVAL.VENDEDOR V (NOLOCK) ON
	DCC.VENDEDOR = V.VENDEDOR
WHERE
	DCC.TIPO = 'FAC'
	AND DCC.DOCUMENTO IN('03205122')
	
	
	
	
	
SELECT DCC.DOCUMENTO AS doc_number,DCC.TIPO AS doc_type,DCC.FECHA_DOCUMENTO AS doc_date,DCC.VENDEDOR AS seller_id,V.NOMBRE AS seller_name,C.NOMBRE AS client_name,C.ZONA AS zone_code,C.E_MAIL AS client_email,V.E_MAIL AS seller_email 
      FROM SOFTLANDPRD.BEVAL.DOCUMENTOS_CC DCC WITH (NOLOCK) 
      INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE C WITH (NOLOCK) ON DCC.CLIENTE = C.CLIENTE 
      INNER JOIN SOFTLANDPRD.BEVAL.VENDEDOR V WITH (NOLOCK) ON DCC.VENDEDOR = V.VENDEDOR 
      WHERE DCC.TIPO = 'FAC' 
      AND DCC.DOCUMENTO IN('03223504')
      UNION
      SELECT F.FACTURA AS doc_number,CASE WHEN F.TIPO_DOCUMENTO = 'F' THEN 'FAC' WHEN F.TIPO_DOCUMENTO = 'D' THEN 'N/C' WHEN F.TIPO_DOCUMENTO = 'C' THEN 'N/D' ELSE 'FAC' END AS doc_type,F.FECHA_RIGE AS doc_date,F.VENDEDOR AS seller_id,V.NOMBRE AS seller_name,C.NOMBRE AS client_name,C.ZONA AS zone_code,C.E_MAIL AS client_email,V.E_MAIL AS seller_email 
      FROM SOFTLANDPRD.BEVAL.FACTURA F WITH (NOLOCK) 
      INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE C WITH (NOLOCK) ON F.CLIENTE = C.CLIENTE 
      INNER JOIN SOFTLANDPRD.BEVAL.VENDEDOR V WITH (NOLOCK) ON F.VENDEDOR = V.VENDEDOR 
      WHERE F.TIPO_DOCUMENTO IS NOT NULL 
      AND F.FACTURA IN('03223504')
      
      
SELECT
	DCC.DOCUMENTO AS doc_number,
	DCC.TIPO AS doc_type,
	DCC.FECHA_DOCUMENTO AS doc_date,
	DCC.VENDEDOR AS seller_id,
	V.NOMBRE AS seller_name,
	C.NOMBRE AS client_name,
	C.ZONA AS zone_code,
	C.E_MAIL AS client_email,
	V.E_MAIL AS seller_email
FROM
	SOFTLANDPRD.BEVAL.DOCUMENTOS_CC DCC (NOLOCK)
INNER JOIN SOFTLANDPRD.BEVAL.CLIENTE C ON
	DCC.CLIENTE = C.CLIENTE
INNER JOIN SOFTLANDPRD.BEVAL.VENDEDOR V (NOLOCK) ON
	DCC.VENDEDOR = V.VENDEDOR
WHERE
	DCC.TIPO = 'FAC'
ORDER BY
	DOCUMENTO OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
