# Esta es la forma correcta como debe quedar
# NC
SELECT * FROM MOVCOMERCIAL WHERE NROMOVFISCAL='01061805';
SELECT * FROM TRANSACCIONES WHERE NUMEROFISCAL='01061805';


# Este es el estado actual:
# NC ACTUAL (INCORRECTO)
SELECT * FROM MOVCOMERCIAL WHERE NROMOVFISCAL='01053625' AND IDDOCUMENTO=3;
SELECT * FROM TRANSACCIONES WHERE NUMEROFISCAL='01053625' AND IDDOCUMENTO=3;


select * from cliente c where IDCLIENTE ='26585'

select * from zonas z where IDZONAS = '39'

select * from colaboradores c where IDCOLABORADORES = '32'

select * from instrumentopago i where IDINSTRUMENTOPAGO = 15


SELECT * FROM MOVCOMERCIAL WHERE  IDMOVCOMERCIAL = 434500;
SELECT * FROM TRANSACCIONES WHERE IDTRANSACCION_SFL =434500;


where IDTRANSACCION = 43450

select max(IDMOVCOMERCIALARTICULO) from movcomercialarticulo m 111015000



SELECT C.IDCLIENTE AS CLIENTE,
# RE.TIPO as 'SBTIPO_CREDITO',
#CASE WHEN RE.TIPO = 'FAC' or RE.TIPO = 'MIX' then (select TIPO from documentocomercial d where d.IDDOCUMENTO = 10) WHEN RE.TIPO = 'N/C' then (select TIPO from documentocomercial d where d.IDDOCUMENTO = 24) END AS 'TIPO',
#CASE WHEN RE.TIPO = 'FAC' or RE.TIPO = 'MIX' then (select SUBTIPO from documentocomercial d where d.IDDOCUMENTO = 10) WHEN RE.TIPO = 'N/C' then (select SUBTIPO from documentocomercial d where d.IDDOCUMENTO = 24) END AS 'SUBTIPO', 
RE.TIPO as 'TIPO', 
CONCAT('RET', SUBSTRING(LP.USERNAME, 2), SUBSTRING(Z.NOMBREZONA, 2), DATE_FORMAT(RE.FECHACREACION, '%y%m%d'), RE.IDRETENCION) AS DOCUMENTO,
'Retenciones Ventas ' AS APLICACION, 
RE.FECHAEMISION AS FECHA_DOCUMENTO, 
M.IDMONEDA AS MONEDA,  
CASE WHEN RE.MONTORETENCION = 0 THEN RE.MONTORETENCION_D ELSE RE.MONTORETENCION END AS MONTO, 
CASE WHEN RE.MONTORETENCION = 0 THEN RE.MONTORETENCION_D ELSE RE.MONTORETENCION END AS MONTO_DOLAR,  
CASE WHEN RE.MONTORETENCION_D = 0 THEN RE.MONTORETENCION_D ELSE RE.MONTORETENCION_D END AS MONTO_LOCAL, 
 'VEN' AS PAIS,
 DC.SUBTIPO AS SUBTIPO,  
 DC.TIPO AS TIPO,  
 CB.IDCOLABORADORES AS VENDEDOR,  
 RE.NUMEROCOMPROBANTE  AS U_Comprobante  
 FROM retencion RE 
 INNER join cliente C ON RE.IDEMISOR = C.IDCLIENTE 
 INNER join documentocomercial DC ON RE.IDDOCUMENTO = DC.IDDOCUMENTO  
 INNER JOIN zonas Z ON RE.IDZONA = Z.IDZONAS  
 INNER JOIN colaboradores CB ON RE.IDCOLABORADOR = CB.IDCOLABORADORES  
 INNER JOIN monedas M ON RE.IDMONEDA = M.IDMONEDA 
 INNER JOIN LoginColaborador LP ON LP.USERNAME = RE.USUARIOCREACION
	where 
		#re.tipo = 'FAC' 
 		#re.tipo = 'MIX'
		RE.tipo = 'N/C'
 		
 		
 select distinct (TIPO) from retencion r 
 
 select * from documentocomercial d  
 
 select * from movcomercial m where 
 
 select * from MOV
 
 WHERE RE.IDRETENCION = ${IDRETENCION} AND RE.IDZONA = ${IDZONA} AND RE.USUARIOCREACION ="${USUARIOCREACION}"`;
 


exports.getRetenciones = (IDRETENCION, IDZONA, USUARIOCREACION) => {
 return `SELECT C.IDCLIENTE AS CLIENTE, RE.TIPO as 'TIPO', 
 CASE WHEN RE.TIPO = 'FAC' or RE.TIPO = 'MIX' then (select TIPO from documentocomercial d where d.IDDOCUMENTO = 10) WHEN RE.TIPO = 'N/C' then (select TIPO from documentocomercial d where d.IDDOCUMENTO = 24) END AS 'TIPO',
CASE WHEN RE.TIPO = 'FAC' or RE.TIPO = 'MIX' then (select SUBTIPO from documentocomercial d where d.IDDOCUMENTO = 10) WHEN RE.TIPO = 'N/C' then (select SUBTIPO from documentocomercial d where d.IDDOCUMENTO = 24) END AS 'SUBTIPO', 
CONCAT('RET', SUBSTRING(LP.USERNAME, 2), SUBSTRING(Z.NOMBREZONA, 2), DATE_FORMAT(RE.FECHACREACION, '%y%m%d'), RE.IDRETENCION) AS DOCUMENTO,
'Retenciones Ventas ' AS APLICACION, 
RE.FECHAEMISION AS FECHA_DOCUMENTO, 
M.IDMONEDA AS MONEDA,  
CASE WHEN RE.MONTORETENCION = 0 THEN RE.MONTORETENCION_D ELSE RE.MONTORETENCION END AS MONTO, 
CASE WHEN RE.MONTORETENCION = 0 THEN RE.MONTORETENCION_D ELSE RE.MONTORETENCION END AS MONTO_DOLAR,  
CASE WHEN RE.MONTORETENCION_D = 0 THEN RE.MONTORETENCION_D ELSE RE.MONTORETENCION_D END AS MONTO_LOCAL, 
 'VEN' AS PAIS, 
 CB.IDCOLABORADORES AS VENDEDOR,  
 RE.NUMEROCOMPROBANTE  AS U_Comprobante  
 FROM retencion RE 
 INNER join cliente C ON RE.IDEMISOR = C.IDCLIENTE 
 INNER join documentocomercial DC ON RE.IDDOCUMENTO = DC.IDDOCUMENTO  
 INNER JOIN zonas Z ON RE.IDZONA = Z.IDZONAS  
 INNER JOIN colaboradores CB ON RE.IDCOLABORADOR = CB.IDCOLABORADORES  
 INNER JOIN monedas M ON RE.IDMONEDA = M.IDMONEDA 
 INNER JOIN LoginColaborador LP ON LP.USERNAME = RE.USUARIOCREACION 
 

SELECT C.IDCLIENTE AS CLIENTE, 
 CONCAT('RET', SUBSTRING(LP.USERNAME, 2), SUBSTRING(Z.NOMBREZONA, 2), DATE_FORMAT(RE.FECHACREACION, '%y%m%d'), RE.IDRETENCION) AS DOCUMENTO,
'Retenciones Ventas ' AS APLICACION, 
RE.FECHAEMISION AS FECHA_DOCUMENTO, 
M.IDMONEDA AS MONEDA,  
CASE WHEN RE.MONTORETENCION = 0 THEN RE.MONTORETENCION_D ELSE RE.MONTORETENCION END AS MONTO, 
CASE WHEN RE.MONTORETENCION = 0 THEN RE.MONTORETENCION_D ELSE RE.MONTORETENCION END AS MONTO_DOLAR,  
CASE WHEN RE.MONTORETENCION_D = 0 THEN RE.MONTORETENCION_D ELSE RE.MONTORETENCION_D END AS MONTO_LOCAL, 
 'VEN' AS PAIS, 
 DC.SUBTIPO AS SUBTIPO,  
 DC.TIPO AS TIPO,  
 CB.IDCOLABORADORES AS VENDEDOR,  
 RE.NUMEROCOMPROBANTE  AS U_Comprobante  
 FROM retencion RE 
 INNER join cliente C ON RE.IDEMISOR = C.IDCLIENTE 
 INNER join documentocomercial DC ON RE.IDDOCUMENTO = DC.IDDOCUMENTO  
 INNER JOIN zonas Z ON RE.IDZONA = Z.IDZONAS  
 INNER JOIN colaboradores CB ON RE.IDCOLABORADOR = CB.IDCOLABORADORES  
 INNER JOIN monedas M ON RE.IDMONEDA = M.IDMONEDA 
 INNER JOIN LoginColaborador LP ON LP.USERNAME = RE.USUARIOCREACION
 where re.TIPO ='MIX'

 
 
  SELECT MVC.NROMOVFISCAL as DEBITO,
 CONCAT('RET', SUBSTRING(LP.USERNAME, 2), SUBSTRING(Z.NOMBREZONA, 2), DATE_FORMAT(RD.FECHACREACION, '%y%m%d'), RD.IDRETENCION) as CREDITO, 
 RD.MONTO as MONTO_DOLAR, 
 RD.MONTO_D as MONTO_LOCAL , 
 CASE WHEN DC.TIPO <>'O/C' THEN DC.TIPO END AS TIPO_DEBITO, 
 'O/C' AS TIPO_CREDITO, 
 CASE WHEN DC.SUBTIPO<>'RETIVA' THEN DC.SUBTIPO END AS SUBTIPO_DEBITO, 
 'RETIVA' AS SUBTIPO_CREDITO 
 FROM retenciondetalle RD 
 INNER JOIN movcomercial MVC ON RD.IDMOVCOMERCIALREF = MVC.IDMOVCOMERCIAL 
 INNER JOIN documentocomercial DC ON MVC.IDDOCUMENTO= DC.IDDOCUMENTO 
 INNER JOIN LoginColaborador LP ON LP.USERNAME= RD.USUARIOCREACION 
 INNER JOIN zonas Z ON Z.IDZONAS= RD.IDZONA 
 
 
 
 
 
 
 
 
 SELECT MVC.NROMOVFISCAL as DEBITO,
 CASE WHEN RE.IDDOCUMENTO = 10 THEN
 CONCAT('RET', SUBSTRING(LP.USERNAME, 2), SUBSTRING(Z.NOMBREZONA, 2), DATE_FORMAT(RE.FECHACREACION, '%y%m%d'), RE.IDRETENCION) 
 ELSE
 CONCAT('RNC', SUBSTRING(LP.USERNAME, 2), SUBSTRING(Z.NOMBREZONA, 2), DATE_FORMAT(RE.FECHACREACION, '%y%m%d'), RE.IDRETENCION)
 AS  CREDITO, 
 RD.MONTO as MONTO_DOLAR, 
 RD.MONTO_D as MONTO_LOCAL,
 CASE WHEN DC.TIPO <>'O/C' THEN DC.TIPO END AS TIPO_DEBITO, 
 'O/C' AS TIPO_CREDITO, 
 CASE WHEN DC.SUBTIPO<>'RETIVA' THEN DC.SUBTIPO END AS SUBTIPO_DEBITO, 
 'RETIVA' AS SUBTIPO_CREDITO 
 FROM retenciondetalle RD 
 INNER JOIN movcomercial MVC ON RD.IDMOVCOMERCIALREF = MVC.IDMOVCOMERCIAL 
 INNER JOIN documentocomercial DC ON MVC.IDDOCUMENTO= DC.IDDOCUMENTO 
 INNER JOIN LoginColaborador LP ON LP.USERNAME= RD.USUARIOCREACION 
 INNER JOIN zonas Z ON Z.IDZONAS= RD.IDZONA
 
 
  SELECT MVC.NROMOVFISCAL as DEBITO,
 CASE WHEN RE.IDDOCUMENTO = 10 THEN
 CONCAT('RET', SUBSTRING(LP.USERNAME, 2), SUBSTRING(Z.NOMBREZONA, 2), DATE_FORMAT(RE.FECHACREACION, '%y%m%d'), RE.IDRETENCION) 
 ELSE
 CONCAT('RNC', SUBSTRING(LP.USERNAME, 2), SUBSTRING(Z.NOMBREZONA, 2), DATE_FORMAT(RE.FECHACREACION, '%y%m%d'), RE.IDRETENCION)
 AS  CREDITO, 
 RD.MONTO as MONTO_DOLAR, 
 RD.MONTO_D as MONTO_LOCAL,
 CASE WHEN DC.TIPO <>'O/C' THEN DC.TIPO END AS TIPO_DEBITO, 
 'O/C' AS TIPO_CREDITO, 
 CASE WHEN DC.SUBTIPO<>'RETIVA' THEN DC.SUBTIPO END AS SUBTIPO_DEBITO, 
 'RETIVA' AS SUBTIPO_CREDITO 
 FROM retenciondetalle RD 
 INNER JOIN movcomercial MVC ON RD.IDMOVCOMERCIALREF = MVC.IDMOVCOMERCIAL 
 INNER JOIN (
 	select  AS siglas, dc.* FROM documentocomercial dc
 ) DC ON MVC.IDDOCUMENTO= DC.IDDOCUMENTO 
 INNER JOIN LoginColaborador LP ON LP.USERNAME= RD.USUARIOCREACION 
 INNER JOIN zonas Z ON Z.IDZONAS= RD.IDZONA
 
 
 RNC003603623082460013
 
 
 
 
 