SELECT * FROM DBAFV.TRANSACCIONES T WHERE T.NUMERODOCUMENTOREF=380937 AND IDDOCUMENTO=10;

60216 - 6965131


SELECT * FROM DBAFV.colaboradores
where NOMBRE1COLABORADOR like '%FERREAGRO MIJA%'

SELECT * FROM DBAFV.logincolaborador limit 10

where NOMBRE1COLABORADOR like '%FERREAGRO MIJA%'


-- buscar recibo por su numero y código del cliente (en afv)
SELECT
R.IDRECIBO,
R.IDZONA,
R.USUARIOCREACION,R.*, C.*
FROM recibo R
INNER JOIN cliente C ON R.IDRECEPTORRECIBO = C.IDCLIENTE
WHERE
R.IDRECIBO = 60216 AND
-- R.IDZONA = 261 AND
C.CODNEMONICO = '6965131';



